### ISSUE TITLE
Symbol not found in libSwiftCore.dylib

### ISSUE THREAD

**Issue by sjrmanning** [terhechte/SourceKittenDaemon#54]
I'm guessing this is because I'm using Xcode 8.3.2, but just wanted to confirm. I'm getting this error after building with `swift build` on master:

```
dyld: lazy symbol binding failed: Symbol not found: __TZFVs24_NativeDictionaryStorage9fromArrayfGSaTxq___GS_xq__
  Referenced from: /Users/simon/Projects/home/forks/SourceKittenDaemon/.build/release/./sourcekittend
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib

dyld: Symbol not found: __TZFVs24_NativeDictionaryStorage9fromArrayfGSaTxq___GS_xq__
  Referenced from: /Users/simon/Projects/home/forks/SourceKittenDaemon/.build/release/./sourcekittend
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib

[1]    44027 abort      ./sourcekittend
```

Any ideas? Anyone else getting the same?

Cheers!

**Comment by nathankot** [comment]
Hey @sjrmanning, are you building on the latest `master`? I've recently pushed 2e09056 which should build correctly on `8.3.2`.

Could you try:

```
git fetch
git checkout master
make clean build
```

**Comment by terhechte** [comment]
@sjrmanning Did it work for you?

**Comment by sjrmanning** [comment]
Yes it did! I think I may have already had this commit but maybe needed the clean. Thanks for the advice, really appreciate the project :)
